name: catenv

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set-env
        env:
          MYENV: ${{ secrets.ENV_SECRET }}
        run: echo $MYENV > e.json

      - name: get-env
        run: cat e.json
